// docs\auth.http
### auth
POST {{host}}
Content-Type: application/json

{
  "query": "mutation Auth($input: AuthInput!) { auth(input: $input) { access_token } }",
  "variables": {
    "input": {
      "email": "{{email}}",
      "password": "{{password}}"
    }
  }
}
