### auth
# @name auth
POST {{host}}
Content-Type: application/json

{
  "query": "mutation Auth($input: AuthInput!) { auth(input: $input) { access_token } }",
  "variables": {
    "input": {
      "email": "{{email}}",
      "password": "{{password}}"
    }
  }
}

### set auth token

@authToken = {{auth.response.body.data.auth.access_token}}

### who
POST {{host}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "query": "query Me { me { id type first_name last_name email phone createdAt updatedAt } }"
}