
###
POST {{host}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  version {
    message
  }
}


###
POST {{host}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmRjZjU0Nzk5ZGNiN2Q3NTVkY2UwZiIsInJvbGUiOiJDT0FDSCIsImVtYWlsIjoiYWxleC5tYXJ0aW5AZXhhbXBsZS5jb20iLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzU3NjExMTM2LCJleHAiOjE3NTc2Mzk5MzZ9.jHPBgQongI0LWbkFGennabtfkrm3ET7Lav6TnAQb8w0
X-REQUEST-TYPE: GraphQL

query {
  db_test {
    message
  }
}