### Create a user (GraphQL)
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation CreateUser($input: CreateUserInput!) { user_create(input: $input) { id type first_name last_name email phone createdAt updatedAt } }",
  "variables": {
    "input": {
      "type": "coach",
      "first_name": "Alex",
      "last_name": "Martin",
      "email": "alex.martin@example.com",
      "phone": "+33612345678",
      "password": "SuperSecret123!",
      "address": {
        "name": "12 rue des Fleurs",
        "city": "Lyon",
        "code": "69003",
        "country": "FR"
      },
      "company": {
        "name": "FitDesk SAS",
        "address": {
          "name": "10 avenue de la République",
          "city": "Paris",
          "code": "75011",
          "country": "FR"
        }
      }
    }
  }
}


### Create a user (GraphQL)
POST http://localhost:3000/graphql
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmRjZjU0Nzk5ZGNiN2Q3NTVkY2UwZiIsInJvbGUiOiJDT0FDSCIsImVtYWlsIjoiYWxleC5tYXJ0aW5AZXhhbXBsZS5jb20iLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzU3NjExMTM2LCJleHAiOjE3NTc2Mzk5MzZ9.jHPBgQongI0LWbkFGennabtfkrm3ET7Lav6TnAQb8w0
Content-Type: application/json

{
  "query": "query Me { me { id type first_name last_name email phone createdAt updatedAt } }"
}
