export enum ERRORS {
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  CRYPT_SERVICE_FAIL = 'CRYPT_SERVICE_FAIL',
  CREATE_USER_USECASE = 'CREATE_USER_USECASE',
  ACCESS_TOKEN_REQUIRED = 'ACCESS_TOKEN_REQUIRED',
  AUTH_PASSKEY_USECASE_FAIL = 'AUTH_PASSKEY_USECASE_FAIL',
  CRYPT_SERVICE_SECRET_WRONG = 'CRYPT_SERVICE_SECRET_WRONG',
  CRYPT_SERVICE_APP_NAME_WRONG = 'CRYPT_SERVICE_APP_NAME_WRONG',
  CREATE_USER_USECASE_FETCH_USER = 'CREATE_USER_USECASE_FETCH_USER',
  GET_USER_USECASE_USER_NOT_FOUND = 'GET_USER_USECASE_USER_NOT_FOUND',
  CREATE_USER_USECASE_USER_ALREADY_EXIST = 'CREATE_USER_USECASE_USER_ALREADY_EXIST',
}
