// src\inversify\investify.ts
import { Db } from 'mongodb';
import { config } from '@src/config';
import { logger } from '@src/common/logger';
import { JwtService } from '@services/jwt/jwt.service';
import { AuthUsecase } from '@usecases/auth/auth.usecase';
import { CryptService } from '@services/crypt/crypt.service';
import { GetTagUsecase } from '@usecases/tag/get.tag.usecase';
import { GetTaskUsecase } from '@usecases/task/get.task.usecase';
import { GetNoteUsecase } from '@usecases/note/get.note.usecase';
import { JwtServiceReal } from '@services/jwt/jwt.service.real';
import { GetUserUsecase } from '@usecases/user/get.user.usecase';
import { DbTestUsecase } from '@usecases/default/db.test.usecase';
import { ListTagsUsecase } from '@usecases/tag/list.tags.usecase';
import { ListTasksUsecase } from '@usecases/task/list.tasks.usecase';
import { ListNotesUsecase } from '@usecases/note/list.notes.usecase';
import { CreateTagUsecase } from '@usecases/tag/create.tag.usecase';
import { CreateTaskUsecase } from '@usecases/task/create.task.usecase';
import { CreateNoteUsecase } from '@usecases/note/create.note.usecase';
import { UpdateTagUsecase } from '@usecases/tag/update.tag.usecase';
import { UpdateTaskUsecase } from '@usecases/task/update.task.usecase';
import { UpdateNoteUsecase } from '@usecases/note/update.note.usecase';
import { DeleteTagUsecase } from '@usecases/tag/delete.tag.usecase';
import { DeleteTaskUsecase } from '@usecases/task/delete.task.usecase';
import { DeleteNoteUsecase } from '@usecases/note/delete.note.usecase';
import { ListUsersUsecase } from '@usecases/user/list.users.usecase';
import { GetMealUsecase } from '@src/usecases/nutri/meal/get.meal.usecase';
import { BddServiceMongo } from '@services/db/mongo/db.service.mongo';
import { CryptServiceReal } from '@services/crypt/crypt.service.real';
import { UpdateUserUsecase } from '@usecases/user/update.user.usecase';
import { CreateUserUsecase } from '@usecases/user/create.user.usecase';
import { DeleteUserUsecase } from '@usecases/user/delete.user.usecase';
import { ListMealsUsecase } from '@src/usecases/nutri/meal/list.meal.usecase';
import { CreateMealUsecase } from '@src/usecases/nutri/meal/create.meal.usecase';
import { UpdateMealUsecase } from '@src/usecases/nutri/meal/update.meal.usecase';
import { DeleteMealUsecase } from '@src/usecases/nutri/meal/delete.meal.usecase';
import { HardDeleteTagUsecase } from '@usecases/tag/hard-delete.tag.usecase';
import { HardDeleteTaskUsecase } from '@usecases/task/hard-delete.task.usecase';
import { HardDeleteNoteUsecase } from '@usecases/note/hard-delete.note.usecase';
import { UpdateMeUsecase } from '@usecases/user/update-me.user.usecase';
import { HardDeleteUserUsecase } from '@usecases/user/hard-delete.user.usecase';
import { GetProgramUsecase } from '@src/usecases/sport/program/get.program.usecase';
import { GetMealDayUsecase } from '@src/usecases/nutri/meal-day/get.meal-day.usecase';
import { GetMuscleUsecase } from '@src/usecases/sport/muscle/get.muscle.usecase';
import { GetSessionUsecase } from '@src/usecases/sport/session/get.session.usecase';
import { GetProspectUsecase } from '@usecases/prospect/prospect/get.prospect.usecase';
import { GetMealTypeUsecase } from '@src/usecases/nutri/meal-type/get.meal-type.usecase';
import { HardDeleteMealUsecase } from '@usecases/nutri/meal/hard-delete.meal.usecase';
import { ListProgramsUsecase } from '@src/usecases/sport/program/list.programs.usecase';
import { UpdateMePasswordUsecase } from '@usecases/user/update-me-password.user.usecase';
import { UpdateProgramUsecase } from '@src/usecases/sport/program/update.program.usecase';
import { DeleteProgramUsecase } from '@src/usecases/sport/program/delete.program.usecase';
import { CreateProgramUsecase } from '@src/usecases/sport/program/create.program.usecase';
import { GetCategoryUsecase } from '@src/usecases/sport/category/get.category.usecase';
import { ListMusclesUsecase } from '@src/usecases/sport/muscle/list.muscles.usecase';
import { UpdateMuscleUsecase } from '@src/usecases/sport/muscle/update.muscle.usecase';
import { DeleteMuscleUsecase } from '@src/usecases/sport/muscle/delete.muscle.usecase';
import { CreateMuscleUsecase } from '@src/usecases/sport/muscle/create.muscle.usecase';
import { ListProspectsUsecase } from '@usecases/prospect/prospect/list.prospects.usecase';
import { UpdateProspectUsecase } from '@usecases/prospect/prospect/update.prospect.usecase';
import { DeleteProspectUsecase } from '@usecases/prospect/prospect/delete.prospect.usecase';
import { CreateProspectUsecase } from '@usecases/prospect/prospect/create.prospect.usecase';
import { GetEquipmentUsecase } from '@src/usecases/sport/equipment/get.equipment.usecase';
import { GetExerciseUsecase } from '@src/usecases/sport/exercise/get.exercise.usecase';
import { CreateMealDayUsecase } from '@src/usecases/nutri/meal-day/create.meal-day.usecase';
import { ListMealDaysUsecase } from '@src/usecases/nutri/meal-day/list.meal-days.usecase';
import { UpdateMealDayUsecase } from '@src/usecases/nutri/meal-day/update.meal-day.usecase';
import { DeleteMealDayUsecase } from '@src/usecases/nutri/meal-day/delete.meal-day.usecase';
import { ListSessionsUsecase } from '@src/usecases/sport/session/list.sessions.usecase';
import { UpdateSessionUsecase } from '@src/usecases/sport/session/update.session.usecase';
import { DeleteSessionUsecase } from '@src/usecases/sport/session/delete.session.usecase';
import { CreateSessionUsecase } from '@src/usecases/sport/session/create.session.usecase';
import { UpdateUserPasswordUsecase } from '@usecases/user/update-password.user.usecase';
import { ListMealTypesUsecase } from '@src/usecases/nutri/meal-type/list.meal-type.usecase';
import { UpdateMealTypeUsecase } from '@src/usecases/nutri/meal-type/update.meal-type.usecase';
import { DeleteMealTypeUsecase } from '@src/usecases/nutri/meal-type/delete.meal-type.usecase';
import { CreateMealTypeUsecase } from '@src/usecases/nutri/meal-type/create.meal-type.usecase';
import { GetMealPlanUsecase } from '@src/usecases/nutri/meal-plan/get.meal-plan.usecase';
import { GetMealRecordUsecase } from '@src/usecases/nutri/meal-record/get.meal-record.usecase';
import { HardDeleteMuscleUsecase } from '@usecases/sport/muscle/hard-delete.muscle.usecase';
import { HardDeleteProgramUsecase } from '@usecases/sport/program/hard-delete.program.usecase';
import { HardDeleteSessionUsecase } from '@usecases/sport/session/hard-delete.session.usecase';
import { ListCoachAthletesUsecase } from '@usecases/athlete/coach-athlete/list.coach-athletes.usecase';
import { UpdateCoachAthleteUsecase } from '@usecases/athlete/coach-athlete/update.coach-athlete.usecase';
import { DeleteCoachAthleteUsecase } from '@usecases/athlete/coach-athlete/delete.coach-athlete.usecase';
import { CreateCoachAthleteUsecase } from '@usecases/athlete/coach-athlete/create.coach-athlete.usecase';
import { GetCoachAthleteUsecase } from '@usecases/athlete/coach-athlete/get.coach-athlete.usecase';
import { GetAthleteInfoUsecase } from '@usecases/athlete/athlete-info/get.athlete-info.usecase';
import { ListCategoriesUsecase } from '@src/usecases/sport/category/list.category.usecase';
import { UpdateCategoryUsecase } from '@src/usecases/sport/category/update.category.usecase';
import { DeleteCategoryUsecase } from '@src/usecases/sport/category/delete.category.usecase';
import { CreateCategoryUsecase } from '@src/usecases/sport/category/create.category.usecase';
import { ListExercisesUsecase } from '@src/usecases/sport/exercise/list.exercises.usecase';
import { UpdateExerciseUsecase } from '@src/usecases/sport/exercise/update.exercise.usecase';
import { DeleteExerciseUsecase } from '@src/usecases/sport/exercise/delete.exercise.usecase';
import { CreateExerciseUsecase } from '@src/usecases/sport/exercise/create.exercise.usecase';
import { ListEquipmentUsecase } from '@src/usecases/sport/equipment/list.equipment.usecase';
import { UpdateEquipmentUsecase } from '@src/usecases/sport/equipment/update.equipment.usecase';
import { DeleteEquipmentUsecase } from '@src/usecases/sport/equipment/delete.equipment.usecase';
import { CreateEquipmentUsecase } from '@src/usecases/sport/equipment/create.equipment.usecase';
import { ListMealPlansUsecase } from '@src/usecases/nutri/meal-plan/list.meal-plans.usecase';
import { UpdateMealPlanUsecase } from '@src/usecases/nutri/meal-plan/update.meal-plan.usecase';
import { DeleteMealPlanUsecase } from '@src/usecases/nutri/meal-plan/delete.meal-plan.usecase';
import { CreateMealPlanUsecase } from '@src/usecases/nutri/meal-plan/create.meal-plan.usecase';
import { GetProgramRecordUsecase } from '@src/usecases/sport/program-record/get.program-record.usecase';
import { HardDeleteMealDayUsecase } from '@usecases/nutri/meal-day/hard-delete.meal-day.usecase';
import { HardDeleteExerciseUsecase } from '@usecases/sport/exercise/hard-delete.exercise.usecase';
import { HardDeleteCategoryUsecase } from '@usecases/sport/category/hard-delete.category.usecase';
import { HardDeleteProspectUsecase } from '@usecases/prospect/hard-delete.prospect.usecase';
import { HardDeleteMealPlanUsecase } from '@usecases/nutri/meal-plan/hard-delete.meal-plan.usecase';
import { HardDeleteMealTypeUsecase } from '@usecases/nutri/meal-type/hard-delete.meal-type.usecase';
import { HardDeleteEquipmentUsecase } from '@usecases/sport/equipment/hard-delete.equipment.usecase';
import { ListAthleteInfosUsecase } from '@usecases/athlete/athlete-info/list.athlete-infos.usecase';
import { UpdateAthleteInfoUsecase } from '@usecases/athlete/athlete-info/update.athlete-info.usecase';
import { DeleteAthleteInfoUsecase } from '@usecases/athlete/athlete-info/delete.athlete-info.usecase';
import { CreateAthleteInfoUsecase } from '@usecases/athlete/athlete-info/create.athlete-info.usecase';
import { ListMealRecordsUsecase } from '@src/usecases/nutri/meal-record/list.meal-records.usecase';
import { UpdateMealRecordUsecase } from '@src/usecases/nutri/meal-record/update.meal-record.usecase';
import { DeleteMealRecordUsecase } from '@src/usecases/nutri/meal-record/delete.meal-record.usecase';
import { CreateMealRecordUsecase } from '@src/usecases/nutri/meal-record/create.meal-record.usecase';
import { GetProspectLevelUsecase } from '@usecases/prospect/level/get.prospect-level.usecase';
import { ConvertProspectToAthleteUsecase } from '@usecases/prospect/prospect/convert.prospect.usecase';
import { GetProspectSourceUsecase } from '@usecases/prospect/source/get.prospect-source.usecase';
import { ListProspectLevelsUsecase } from '@usecases/prospect/level/list.prospect-level.usecase';
import { UpdateProspectLevelUsecase } from '@usecases/prospect/level/update.prospect-level.usecase';
import { DeleteProspectLevelUsecase } from '@usecases/prospect/level/delete.prospect-level.usecase';
import { CreateProspectLevelUsecase } from '@usecases/prospect/level/create.prospect-level.usecase';
import { ListProgramRecordsUsecase } from '@src/usecases/sport/program-record/list.program-records.usecase';
import { UpdateProgramRecordUsecase } from '@src/usecases/sport/program-record/update.program-record.usecase';
import { DeleteProgramRecordUsecase } from '@src/usecases/sport/program-record/delete.program-record.usecase';
import { CreateProgramRecordUsecase } from '@src/usecases/sport/program-record/create.program-record.usecase';
import { HardDeleteAthleteInfoUsecase } from '@usecases/athlete/athlete-info/hard-delete.athlete-info.usecase';
import { HardDeleteMealRecordUsecase } from '@src/usecases/nutri/meal-record/hard-delete.meal-record.usecase';
import { GetProspectObjectiveUsecase } from '@usecases/prospect/objective/get.prospect-objective.usecase';
import { ListProspectSourcesUsecase } from '@usecases/prospect/source/list.prospect-source.usecase';
import { UpdateProspectSourceUsecase } from '@usecases/prospect/source/update.prospect-source.usecase';
import { DeleteProspectSourceUsecase } from '@usecases/prospect/source/delete.prospect-source.usecase';
import { CreateProspectSourceUsecase } from '@usecases/prospect/source/create.prospect-source.usecase';
import { HardDeleteProspectLevelUsecase } from '@usecases/prospect/level/hard-delete.prospect-level.usecase';
import { HardDeleteProspectSourceUsecase } from '@usecases/prospect/source/hard-delete.prospect-source.usecase';
import { ListProspectObjectivesUsecase } from '@usecases/prospect/objective/list.prospect-objective.usecase';
import { UpdateProspectObjectiveUsecase } from '@usecases/prospect/objective/update.prospect-objective.usecase';
import { DeleteProspectObjectiveUsecase } from '@usecases/prospect/objective/delete.prospect-objective.usecase';
import { CreateProspectObjectiveUsecase } from '@usecases/prospect/objective/create.prospect-objective.usecase';
import { HardDeleteProgramRecordUsecase } from '@src/usecases/sport/program-record/hard-delete.program-record.usecase';
import { HardDeleteCoachAthleteLinkUsecase } from '@usecases/athlete/coach-athlete/hard-delete.coach-athlete.usecase';
import { HardDeleteProspectObjectiveUsecase } from '@usecases/prospect/objective/hard-delete.prospect-objective.usecase';
import { GetProspectActivityPreferenceUsecase } from '@usecases/prospect/activity-preference/get.prospect-activity-preference.usecase';
import { ListProspectActivityPreferencesUsecase } from '@usecases/prospect/activity-preference/list.prospect-activity-preference.usecase';
import { UpdateProspectActivityPreferenceUsecase } from '@usecases/prospect/activity-preference/update.prospect-activity-preference.usecase';
import { DeleteProspectActivityPreferenceUsecase } from '@usecases/prospect/activity-preference/delete.prospect-activity-preference.usecase';
import { CreateProspectActivityPreferenceUsecase } from '@usecases/prospect/activity-preference/create.prospect-activity-preference.usecase';
import { HardDeleteProspectActivityPreferenceUsecase } from '@usecases/prospect/activity-preference/hard-delete.prospect-activity-preference.usecase';


export class Inversify {
  mongo: Db;
  loggerService: any;
  jwtService: JwtService;
  authUsecase: AuthUsecase;
  cryptService: CryptService;
  bddService: BddServiceMongo;
  dbTestUsecase: DbTestUsecase;
  getTagUsecase: GetTagUsecase;
  getTaskUsecase: GetTaskUsecase;
  getNoteUsecase: GetNoteUsecase;
  getUserUsecase: GetUserUsecase;
  listTagsUsecase: ListTagsUsecase;
  listTasksUsecase: ListTasksUsecase;
  listNotesUsecase: ListNotesUsecase;
  listUsersUsecase: ListUsersUsecase;
  updateTagUsecase: UpdateTagUsecase;
  updateTaskUsecase: UpdateTaskUsecase;
  updateNoteUsecase: UpdateNoteUsecase;
  deleteTagUsecase: DeleteTagUsecase;
  deleteTaskUsecase: DeleteTaskUsecase;
  deleteNoteUsecase: DeleteNoteUsecase;
  createTagUsecase: CreateTagUsecase;
  createTaskUsecase: CreateTaskUsecase;
  createNoteUsecase: CreateNoteUsecase;
  getMuscleUsecase: GetMuscleUsecase;
  updateUserUsecase: UpdateUserUsecase;
  createUserUsecase: CreateUserUsecase;
  deleteUserUsecase: DeleteUserUsecase;
  hardDeleteUserUsecase: HardDeleteUserUsecase;
  updateUserPasswordUsecase: UpdateUserPasswordUsecase;
  updateMeUsecase: UpdateMeUsecase;
  updateMePasswordUsecase: UpdateMePasswordUsecase;
  getSessionUsecase: GetSessionUsecase;
  getProgramUsecase: GetProgramUsecase;
  getCategoryUsecase: GetCategoryUsecase;
  listMusclesUsecase: ListMusclesUsecase;
  getExerciseUsecase: GetExerciseUsecase;
  updateMuscleUsecase: UpdateMuscleUsecase;
  deleteMuscleUsecase: DeleteMuscleUsecase;
  getEquipmentUsecase: GetEquipmentUsecase;
  createMuscleUsecase: CreateMuscleUsecase;
  listSessionsUsecase: ListSessionsUsecase;
  listProgramsUsecase: ListProgramsUsecase;
  listProgramRecordsUsecase: ListProgramRecordsUsecase;
  listEquipmentUsecase: ListEquipmentUsecase;
  listExercisesUsecase: ListExercisesUsecase;
  createSessionUsecase: CreateSessionUsecase;
  deleteSessionUsecase: DeleteSessionUsecase;
  updateSessionUsecase: UpdateSessionUsecase;
  createProgramUsecase: CreateProgramUsecase;
  createProgramRecordUsecase: CreateProgramRecordUsecase;
  deleteProgramUsecase: DeleteProgramUsecase;
  updateProgramUsecase: UpdateProgramUsecase;
  updateProgramRecordUsecase: UpdateProgramRecordUsecase;
  deleteProgramRecordUsecase: DeleteProgramRecordUsecase;
  hardDeleteProgramRecordUsecase: HardDeleteProgramRecordUsecase;
  getProgramRecordUsecase: GetProgramRecordUsecase;
  updateCategoryUsecase: UpdateCategoryUsecase;
  createCategoryUsecase: CreateCategoryUsecase;
  listCategoriesUsecase: ListCategoriesUsecase;
  deleteCategoryUsecase: DeleteCategoryUsecase;
  getClientObjectiveUsecase: GetProspectObjectiveUsecase;
  createClientObjectiveUsecase: CreateProspectObjectiveUsecase;
  listClientObjectivesUsecase: ListProspectObjectivesUsecase;
  updateClientObjectiveUsecase: UpdateProspectObjectiveUsecase;
  deleteClientObjectiveUsecase: DeleteProspectObjectiveUsecase;
  getClientActivityPreferenceUsecase: GetProspectActivityPreferenceUsecase;
  createClientActivityPreferenceUsecase: CreateProspectActivityPreferenceUsecase;
  listClientActivityPreferencesUsecase: ListProspectActivityPreferencesUsecase;
  updateClientActivityPreferenceUsecase: UpdateProspectActivityPreferenceUsecase;
  deleteClientActivityPreferenceUsecase: DeleteProspectActivityPreferenceUsecase;
  getClientLevelUsecase: GetProspectLevelUsecase;
  createClientLevelUsecase: CreateProspectLevelUsecase;
  listClientLevelsUsecase: ListProspectLevelsUsecase;
  updateClientLevelUsecase: UpdateProspectLevelUsecase;
  deleteClientLevelUsecase: DeleteProspectLevelUsecase;
  getClientSourceUsecase: GetProspectSourceUsecase;
  createClientSourceUsecase: CreateProspectSourceUsecase;
  listClientSourcesUsecase: ListProspectSourcesUsecase;
  updateClientSourceUsecase: UpdateProspectSourceUsecase;
  deleteClientSourceUsecase: DeleteProspectSourceUsecase;
  getProspectUsecase: GetProspectUsecase;
  createProspectUsecase: CreateProspectUsecase;
  listProspectsUsecase: ListProspectsUsecase;
  convertProspectToAthleteUsecase: ConvertProspectToAthleteUsecase;
  updateProspectUsecase: UpdateProspectUsecase;
  deleteProspectUsecase: DeleteProspectUsecase;
  getCoachAthleteUsecase: GetCoachAthleteUsecase;
  createCoachAthleteUsecase: CreateCoachAthleteUsecase;
  listCoachAthletesUsecase: ListCoachAthletesUsecase;
  updateCoachAthleteUsecase: UpdateCoachAthleteUsecase;
  deleteCoachAthleteUsecase: DeleteCoachAthleteUsecase;
  getAthleteInfoUsecase: GetAthleteInfoUsecase;
  createAthleteInfoUsecase: CreateAthleteInfoUsecase;
  listAthleteInfosUsecase: ListAthleteInfosUsecase;
  updateAthleteInfoUsecase: UpdateAthleteInfoUsecase;
  deleteAthleteInfoUsecase: DeleteAthleteInfoUsecase;
  hardDeleteAthleteInfoUsecase: HardDeleteAthleteInfoUsecase;
  getMealTypeUsecase: GetMealTypeUsecase;
  listMealTypesUsecase: ListMealTypesUsecase;
  createMealTypeUsecase: CreateMealTypeUsecase;
  updateMealTypeUsecase: UpdateMealTypeUsecase;
  deleteMealTypeUsecase: DeleteMealTypeUsecase;
  createExerciseUsecase: CreateExerciseUsecase;
  deleteExerciseUsecase: DeleteExerciseUsecase;
  updateExerciseUsecase: UpdateExerciseUsecase;
  createEquipmentUsecase: CreateEquipmentUsecase;
  updateEquipmentUsecase: UpdateEquipmentUsecase;
  deleteEquipmentUsecase: DeleteEquipmentUsecase;
  createMealUsecase: CreateMealUsecase;
  getMealUsecase: GetMealUsecase;
  listMealsUsecase: ListMealsUsecase;
  updateMealUsecase: UpdateMealUsecase;
  deleteMealUsecase: DeleteMealUsecase;
  createMealDayUsecase: CreateMealDayUsecase;
  getMealDayUsecase: GetMealDayUsecase;
  listMealDaysUsecase: ListMealDaysUsecase;
  updateMealDayUsecase: UpdateMealDayUsecase;
  deleteMealDayUsecase: DeleteMealDayUsecase;
  createMealPlanUsecase: CreateMealPlanUsecase;
  getMealPlanUsecase: GetMealPlanUsecase;
  listMealPlansUsecase: ListMealPlansUsecase;
  updateMealPlanUsecase: UpdateMealPlanUsecase;
  deleteMealPlanUsecase: DeleteMealPlanUsecase;
  getMealRecordUsecase: GetMealRecordUsecase;
  listMealRecordsUsecase: ListMealRecordsUsecase;
  createMealRecordUsecase: CreateMealRecordUsecase;
  updateMealRecordUsecase: UpdateMealRecordUsecase;
  deleteMealRecordUsecase: DeleteMealRecordUsecase;
  hardDeleteMealRecordUsecase: HardDeleteMealRecordUsecase;

  // Hard Delete Use Cases
  hardDeleteProspectActivityPreferenceUsecase: HardDeleteProspectActivityPreferenceUsecase;
  hardDeleteProspectLevelUsecase: HardDeleteProspectLevelUsecase;
  hardDeleteProspectObjectiveUsecase: HardDeleteProspectObjectiveUsecase;
  hardDeleteProspectSourceUsecase: HardDeleteProspectSourceUsecase;
  hardDeleteProspectUsecase: HardDeleteProspectUsecase;
  hardDeleteTagUsecase: HardDeleteTagUsecase;
  hardDeleteTaskUsecase: HardDeleteTaskUsecase;
  hardDeleteNoteUsecase: HardDeleteNoteUsecase;
  hardDeleteSessionUsecase: HardDeleteSessionUsecase;
  hardDeleteProgramUsecase: HardDeleteProgramUsecase;
  hardDeleteMuscleUsecase: HardDeleteMuscleUsecase;
  hardDeleteExerciseUsecase: HardDeleteExerciseUsecase;
  hardDeleteEquipmentUsecase: HardDeleteEquipmentUsecase;
  hardDeleteCategoryUsecase: HardDeleteCategoryUsecase;
  hardDeleteMealUsecase: HardDeleteMealUsecase;
  hardDeleteMealTypeUsecase: HardDeleteMealTypeUsecase;
  hardDeleteMealPlanUsecase: HardDeleteMealPlanUsecase;
  hardDeleteMealDayUsecase: HardDeleteMealDayUsecase;
  hardDeleteCoachAthleteLinkUsecase: HardDeleteCoachAthleteLinkUsecase;


  constructor() {
    /**
     * Services
     */
    this.loggerService = logger;
    this.cryptService = new CryptServiceReal();
    this.jwtService = new JwtServiceReal(config);
    this.bddService = new BddServiceMongo({
      inversify: this,
      config,
    });
    void this.bddService.init.initConnection();

    /**
     * Usecases
     */
    this.authUsecase = new AuthUsecase(this);
    this.dbTestUsecase = new DbTestUsecase(this);
    // usecases tag
    this.getTagUsecase = new GetTagUsecase(this);
    this.listTagsUsecase = new ListTagsUsecase(this);
    this.createTagUsecase = new CreateTagUsecase(this);
    this.updateTagUsecase = new UpdateTagUsecase(this);
    this.deleteTagUsecase = new DeleteTagUsecase(this);
    // usecases task
    this.getTaskUsecase = new GetTaskUsecase(this);
    this.listTasksUsecase = new ListTasksUsecase(this);
    this.createTaskUsecase = new CreateTaskUsecase(this);
    this.updateTaskUsecase = new UpdateTaskUsecase(this);
    this.deleteTaskUsecase = new DeleteTaskUsecase(this);
    // usecases note
    this.getNoteUsecase = new GetNoteUsecase(this);
    this.listNotesUsecase = new ListNotesUsecase(this);
    this.createNoteUsecase = new CreateNoteUsecase(this);
    this.updateNoteUsecase = new UpdateNoteUsecase(this);
    this.deleteNoteUsecase = new DeleteNoteUsecase(this);
    // usecases user
    this.getUserUsecase = new GetUserUsecase(this);
    this.createUserUsecase = new CreateUserUsecase(this);
    this.listUsersUsecase = new ListUsersUsecase(this);
    this.updateUserUsecase = new UpdateUserUsecase(this);
    this.deleteUserUsecase = new DeleteUserUsecase(this);
    this.hardDeleteUserUsecase = new HardDeleteUserUsecase(this);
    this.updateUserPasswordUsecase = new UpdateUserPasswordUsecase(this);
    this.updateMeUsecase = new UpdateMeUsecase(this);
    this.updateMePasswordUsecase = new UpdateMePasswordUsecase(this);
    // usecases category
    this.getCategoryUsecase = new GetCategoryUsecase(this);
    this.createCategoryUsecase = new CreateCategoryUsecase(this);
    this.listCategoriesUsecase = new ListCategoriesUsecase(this);
    this.updateCategoryUsecase = new UpdateCategoryUsecase(this);
    this.deleteCategoryUsecase = new DeleteCategoryUsecase(this);
    // usecases muscle
    this.getMuscleUsecase = new GetMuscleUsecase(this);
    this.listMusclesUsecase = new ListMusclesUsecase(this);
    this.createMuscleUsecase = new CreateMuscleUsecase(this);
    this.updateMuscleUsecase = new UpdateMuscleUsecase(this);
    this.deleteMuscleUsecase = new DeleteMuscleUsecase(this);
    // usecases equipment
    this.getEquipmentUsecase = new GetEquipmentUsecase(this);
    this.listEquipmentUsecase = new ListEquipmentUsecase(this);
    this.createEquipmentUsecase = new CreateEquipmentUsecase(this);
    this.updateEquipmentUsecase = new UpdateEquipmentUsecase(this);
    this.deleteEquipmentUsecase = new DeleteEquipmentUsecase(this);
    // usecases exercise
    this.getExerciseUsecase = new GetExerciseUsecase(this);
    this.listExercisesUsecase = new ListExercisesUsecase(this);
    this.createExerciseUsecase = new CreateExerciseUsecase(this);
    this.updateExerciseUsecase = new UpdateExerciseUsecase(this);
    this.deleteExerciseUsecase = new DeleteExerciseUsecase(this);
    // usecases session
    this.getSessionUsecase = new GetSessionUsecase(this);
    this.listSessionsUsecase = new ListSessionsUsecase(this);
    this.createSessionUsecase = new CreateSessionUsecase(this);
    this.updateSessionUsecase = new UpdateSessionUsecase(this);
    this.deleteSessionUsecase = new DeleteSessionUsecase(this);
    // usecases program
    this.getProgramUsecase = new GetProgramUsecase(this);
    this.listProgramsUsecase = new ListProgramsUsecase(this);
    this.createProgramUsecase = new CreateProgramUsecase(this);
    this.updateProgramUsecase = new UpdateProgramUsecase(this);
    this.deleteProgramUsecase = new DeleteProgramUsecase(this);
    // usecases program records
    this.getProgramRecordUsecase = new GetProgramRecordUsecase(this);
    this.listProgramRecordsUsecase = new ListProgramRecordsUsecase(this);
    this.createProgramRecordUsecase = new CreateProgramRecordUsecase(this);
    this.updateProgramRecordUsecase = new UpdateProgramRecordUsecase(this);
    this.deleteProgramRecordUsecase = new DeleteProgramRecordUsecase(this);
    this.hardDeleteProgramRecordUsecase = new HardDeleteProgramRecordUsecase(this);
    // usecases client objective
    this.getClientObjectiveUsecase = new GetProspectObjectiveUsecase(this);
    this.createClientObjectiveUsecase = new CreateProspectObjectiveUsecase(this);
    this.listClientObjectivesUsecase = new ListProspectObjectivesUsecase(this);
    this.updateClientObjectiveUsecase = new UpdateProspectObjectiveUsecase(this);
    this.deleteClientObjectiveUsecase = new DeleteProspectObjectiveUsecase(this);
    // usecases client activity preference
    this.getClientActivityPreferenceUsecase = new GetProspectActivityPreferenceUsecase(this);
    this.createClientActivityPreferenceUsecase = new CreateProspectActivityPreferenceUsecase(this);
    this.listClientActivityPreferencesUsecase = new ListProspectActivityPreferencesUsecase(this);
    this.updateClientActivityPreferenceUsecase = new UpdateProspectActivityPreferenceUsecase(this);
    this.deleteClientActivityPreferenceUsecase = new DeleteProspectActivityPreferenceUsecase(this);
    // usecases client level
    this.getClientLevelUsecase = new GetProspectLevelUsecase(this);
    this.createClientLevelUsecase = new CreateProspectLevelUsecase(this);
    this.listClientLevelsUsecase = new ListProspectLevelsUsecase(this);
    this.updateClientLevelUsecase = new UpdateProspectLevelUsecase(this);
    this.deleteClientLevelUsecase = new DeleteProspectLevelUsecase(this);
    // usecases client source
    this.getClientSourceUsecase = new GetProspectSourceUsecase(this);
    this.createClientSourceUsecase = new CreateProspectSourceUsecase(this);
    this.listClientSourcesUsecase = new ListProspectSourcesUsecase(this);
    this.updateClientSourceUsecase = new UpdateProspectSourceUsecase(this);
    this.deleteClientSourceUsecase = new DeleteProspectSourceUsecase(this);
    // usecases prospect
    this.getProspectUsecase = new GetProspectUsecase(this);
    this.createProspectUsecase = new CreateProspectUsecase(this);
    this.listProspectsUsecase = new ListProspectsUsecase(this);
    this.convertProspectToAthleteUsecase = new ConvertProspectToAthleteUsecase(this);
    this.updateProspectUsecase = new UpdateProspectUsecase(this);
    this.deleteProspectUsecase = new DeleteProspectUsecase(this);
    // usecases coach athlete
    this.getCoachAthleteUsecase = new GetCoachAthleteUsecase(this);
    this.createCoachAthleteUsecase = new CreateCoachAthleteUsecase(this);
    this.listCoachAthletesUsecase = new ListCoachAthletesUsecase(this);
    this.updateCoachAthleteUsecase = new UpdateCoachAthleteUsecase(this);
    this.deleteCoachAthleteUsecase = new DeleteCoachAthleteUsecase(this);
    // usecases athlete info
    this.getAthleteInfoUsecase = new GetAthleteInfoUsecase(this);
    this.createAthleteInfoUsecase = new CreateAthleteInfoUsecase(this);
    this.listAthleteInfosUsecase = new ListAthleteInfosUsecase(this);
    this.updateAthleteInfoUsecase = new UpdateAthleteInfoUsecase(this);
    this.deleteAthleteInfoUsecase = new DeleteAthleteInfoUsecase(this);
    this.hardDeleteAthleteInfoUsecase = new HardDeleteAthleteInfoUsecase(this);
    // usecases meal type
    this.createMealTypeUsecase = new CreateMealTypeUsecase(this);
    this.getMealTypeUsecase = new GetMealTypeUsecase(this);
    this.listMealTypesUsecase = new ListMealTypesUsecase(this);
    this.updateMealTypeUsecase = new UpdateMealTypeUsecase(this);
    this.deleteMealTypeUsecase = new DeleteMealTypeUsecase(this);
    // usecases meal
    this.createMealUsecase = new CreateMealUsecase(this);
    this.getMealUsecase = new GetMealUsecase(this);
    this.listMealsUsecase = new ListMealsUsecase(this);
    this.updateMealUsecase = new UpdateMealUsecase(this);
    this.deleteMealUsecase = new DeleteMealUsecase(this);
    // usecases meal day
    this.createMealDayUsecase = new CreateMealDayUsecase(this);
    this.getMealDayUsecase = new GetMealDayUsecase(this);
    this.listMealDaysUsecase = new ListMealDaysUsecase(this);
    this.updateMealDayUsecase = new UpdateMealDayUsecase(this);
    this.deleteMealDayUsecase = new DeleteMealDayUsecase(this);
    // usecases meal plan
    this.createMealPlanUsecase = new CreateMealPlanUsecase(this);
    this.getMealPlanUsecase = new GetMealPlanUsecase(this);
    this.listMealPlansUsecase = new ListMealPlansUsecase(this);
    this.updateMealPlanUsecase = new UpdateMealPlanUsecase(this);
    this.deleteMealPlanUsecase = new DeleteMealPlanUsecase(this);
    // usecases meal records
    this.getMealRecordUsecase = new GetMealRecordUsecase(this);
    this.listMealRecordsUsecase = new ListMealRecordsUsecase(this);
    this.createMealRecordUsecase = new CreateMealRecordUsecase(this);
    this.updateMealRecordUsecase = new UpdateMealRecordUsecase(this);
    this.deleteMealRecordUsecase = new DeleteMealRecordUsecase(this);
    this.hardDeleteMealRecordUsecase = new HardDeleteMealRecordUsecase(this);

    // Hard delete instantiations
    this.hardDeleteProspectActivityPreferenceUsecase = new HardDeleteProspectActivityPreferenceUsecase(this);
    this.hardDeleteProspectLevelUsecase = new HardDeleteProspectLevelUsecase(this);
    this.hardDeleteProspectObjectiveUsecase = new HardDeleteProspectObjectiveUsecase(this);
    this.hardDeleteProspectSourceUsecase = new HardDeleteProspectSourceUsecase(this);
    this.hardDeleteProspectUsecase = new HardDeleteProspectUsecase(this);
    this.hardDeleteTagUsecase = new HardDeleteTagUsecase(this);
    this.hardDeleteTaskUsecase = new HardDeleteTaskUsecase(this);
    this.hardDeleteNoteUsecase = new HardDeleteNoteUsecase(this);
    this.hardDeleteSessionUsecase = new HardDeleteSessionUsecase(this);
    this.hardDeleteProgramUsecase = new HardDeleteProgramUsecase(this);
    this.hardDeleteMuscleUsecase = new HardDeleteMuscleUsecase(this);
    this.hardDeleteExerciseUsecase = new HardDeleteExerciseUsecase(this);
    this.hardDeleteEquipmentUsecase = new HardDeleteEquipmentUsecase(this);
    this.hardDeleteCategoryUsecase = new HardDeleteCategoryUsecase(this);
    this.hardDeleteMealUsecase = new HardDeleteMealUsecase(this);
    this.hardDeleteMealTypeUsecase = new HardDeleteMealTypeUsecase(this);
    this.hardDeleteMealPlanUsecase = new HardDeleteMealPlanUsecase(this);
    this.hardDeleteMealDayUsecase = new HardDeleteMealDayUsecase(this);
    this.hardDeleteCoachAthleteLinkUsecase = new HardDeleteCoachAthleteLinkUsecase(this);
  }
}

const inversify = new Inversify();

export default inversify;
